# Generated by Django 3.2 on 2021-06-13 20:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_random_code, max_length=8, unique=True)),
                ('host_name', models.CharField(max_length=50)),
                ('current_players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=4)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
