# Generated by Django 3.2 on 2021-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
