# Generated by Django 3.2 on 2021-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dictionaryword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DictionaryWord',
        ),
        migrations.AddField(
            model_name='room',
            name='current_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
    ]
