# Generated by Django 3.2 on 2021-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210419_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_name',
            field=models.CharField(default='d4Player', max_length=50),
            preserve_default=False,
        ),
    ]
